# Generated by Django 4.0.4 on 2022-08-17 19:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Restaurant', max_length=255)),
                ('lng', models.DecimalField(decimal_places=3, max_digits=255)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=255)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
